export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_POKEMONS_TYPES = 'SET_POKEMONS_TYPES';
export const SET_POKEMONS_SUBTYPES = 'SET_POKEMONS_SUBTYPES';
export const SET_TYPES_VALUE = 'SET_TYPES_VALUE';
export const SET_SUBTYPES_VALUE = 'SET_SUBTYPES_VALUE';
export const SET_LOADING = 'SET_LOADING';